In [ ]:
# Logistic Regression

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import warnings
warnings.filterwarnings("ignore")

In [4]:
df=pd.read_csv("Titanic-Dataset (2).csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [7]:
df.shape

(891, 12)

In [8]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 118.9 KB

In [10]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [14]:
df.describe(include="O")

                           Name   Sex  Ticket Cabin Embarked
count                       891   891     891   204      889
unique                      891     2     681   147        3
top     Braund, Mr. Owen Harris  male  347082    G6        S
freq                          1   577       7     4      644

In [16]:
data=df[['Pclass',"Sex","Age","SibSp","Parch","Fare","Embarked","Survived"]]

In [18]:
data["Family_Size"]=data['SibSp']+data["Parch"] +1

In [19]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Pclass       891 non-null    int64
 1   Sex          891 non-null    str
 2   Age          714 non-null    float64
 3   SibSp        891 non-null    int64
 4   Parch        891 non-null    int64
 5   Fare         891 non-null    float64
 6   Embarked     889 non-null    str
 7   Survived     891 non-null    int64
 8   Family_Size  891 non-null    int64
dtypes: float64(2), int64(5), str(2)
memory usage: 67.8 KB

In [20]:
data['Age']=data['Age'].fillna(round(data["Age"].mean(),0)).astype(int)

In [21]:
A=data["Embarked"].mode()[0]

In [22]:
data["Embarked"].fillna(A,inplace=True)

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: str

In [23]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Pclass       891 non-null    int64
 1   Sex          891 non-null    str
 2   Age          891 non-null    int64
 3   SibSp        891 non-null    int64
 4   Parch        891 non-null    int64
 5   Fare         891 non-null    float64
 6   Embarked     889 non-null    str
 7   Survived     891 non-null    int64
 8   Family_Size  891 non-null    int64
dtypes: float64(1), int64(6), str(2)
memory usage: 67.8 KB

In [25]:
data.duplicated().sum()

np.int64(122)

In [27]:
data.reset_index(drop=True)

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Survived,Family_Size
0,3,male,22,1,0,7.2500,S,0,2
1,1,female,38,1,0,71.2833,C,1,2
2,3,female,26,0,0,7.9250,S,1,1
3,1,female,35,1,0,53.1000,S,1,2
4,3,male,35,0,0,8.0500,S,0,1
...,...,...,...,...,...,...,...,...,...
886,2,male,27,0,0,13.0000,S,0,1
887,1,female,19,0,0,30.0000,S,1,1
888,3,female,30,1,2,23.4500,S,0,4
889,1,male,26,0,0,30.0000,C,1,1
890,3,male,32,0,0,7.7500,Q,0,1

In [30]:
from sklearn.preprocessing import LabelEncoder

In [32]:
encoder=LabelEncoder()

In [34]:
data["Sex"]=encoder.fit_transform(data["Sex"])
data["Embarked"]=encoder.fit_transform(data["Embarked"])

In [35]:
data

     Pclass  Sex  Age  SibSp  Parch     Fare  Embarked  Survived  Family_Size
0         3    1   22      1      0   7.2500         2         0            2
1         1    0   38      1      0  71.2833         0         1            2
2         3    0   26      0      0   7.9250         2         1            1
3         1    0   35      1      0  53.1000         2         1            2
4         3    1   35      0      0   8.0500         2         0            1
..      ...  ...  ...    ...    ...      ...       ...       ...          ...
886       2    1   27      0      0  13.0000         2         0            1
887       1    0   19      0      0  30.0000         2         1            1
888       3    0   30      1      2  23.4500         2         0            4
889       1    1   26      0      0  30.0000         0         1            1
890       3    1   32      0      0   7.7500         1         0            1

[891 rows x 9 columns]

In [36]:
x=data.drop("Survived",axis=1)
y=data["Survived"]

In [37]:
from sklearn.model_selection import train_test_split as tts

In [38]:
x_train,x_test,y_train,y_test = tts(x,y,test_size=0.3,random_state=21)

In [39]:
from sklearn.linear_model import LogisticRegression
LGR=LogisticRegression

In [42]:
model=LGR.fit(x_train,y_train)

AttributeError: 'DataFrame' object has no attribute '_validate_params'

In [ ]:
y_pred=model.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [ ]:
score=accuracy_score(y_test,y_pred)
score

In [ ]:
confusion_matrix(y_test,y_pred)